// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using X0Game.Data;

#nullable disable

namespace X0Game.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250722122441_ChangeFieldTo2DArray")]
    partial class ChangeFieldTo2DArray
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("X0Game.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameId"));

                    b.Property<int>("CounterOfMoves")
                        .HasColumnType("integer")
                        .HasColumnName("game_counter_of_moves");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field");

                    b.Property<int>("FieldSize")
                        .HasColumnType("integer")
                        .HasColumnName("field_size");

                    b.Property<string>("GameStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NextPlayer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("next_player");

                    b.Property<int>("VictoryCondition")
                        .HasColumnType("integer")
                        .HasColumnName("vicory_condition");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
