name: .NET Build and Test

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 

    - name: Setup .NET
      uses: actions/setup-dotnet@v3 
      with:
        dotnet-version: 8.0.x 

    - name: Restore dependencies
      run: dotnet restore "X0Game.sln"

    - name: Build
      run: dotnet build "X0Game.sln" --no-restore 

    - name: Test
      continue-on-error: true 
      run: dotnet test "X0Game.sln" --no-build --verbosity normal 